server:
  port: ${PORT:8080}
  servlet:
    context-path: /pharmacy
spring:
  application:
    name: ${DBMS_NAME}
  datasource:
    url: ${DBMS_CONNECTION}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  sendgrid:
    api-key: ${SENDGRID_API_KEY}
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${MAIL_USERNAME}
#    password: ${MAIL_PASSWORD}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS}
    username: ${ELASTICSEARCH_USERNAME}
    password: ${ELASTICSEARCH_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      connect-timeout: 5000ms
    elasticsearch:
      repositories:
        enabled: true
#Goole OAuth2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 30MB

jwt:
  signerKey: ${JWT_SECRET}
  valid-duration: 20000 # in second
  refreshable-duration: 120000 # in seconds
outbound:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
vnpay:
  tmn-code: ${VNPAY_TMN_CODE}
  hash-secret: ${VNPAY_HASH_SECRET}
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: ${RETURN_URL}
  ipn-url: ${IPN_URL}
  api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${API_KEY_CLOUD}
  api-secret: ${API_SECRET_CLOUD}
